name = "render-raster"
main = "index.ts"

compatibility_date = "2024-12-16"
compatibility_flags = [ "nodejs_compat" ]

upload_source_maps = true

[[kv_namespaces]]
binding = "KV"
id = "xxx"
preview_id = "xxx"

[browser]
binding = "BROWSER"
